export const CREAT_ORDER_REQUEST="CREAT_ORDER_REQUEST";
export const CREAT_ORDER_SUCCESS="CREAT_ORDER_SUCCESS";
export const CREAT_ORDER_FAIL="CREAT_ORDER_FAIL";

export const MY_ORDER_REQUEST=" MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS=" MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL=" MY_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";
